# 目标：编译、运行并删除 test 测试程序

fopen_test : fopen_test.c
	$(CC) -o $@ $^   # 编译生成可执行文件
	./$@             
	rm ./$@                

fclose_test : fclose_test.c
	$(CC) -o $@ $^   # 编译生成可执行文件
	./$@             
	rm ./$@                        

fputc_test : fputc_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@                      

fputs_test : fputs_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@  

fprintf_test : fprintf_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@        

fgetc_test : fgetc_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@    

fgets_test : fgets_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@    

fscanf_test : fscanf_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@    

stdin_out_err_test : stdin_out_err_test.c
	$(CC) -o $@ $^   
	./$@             
	rm ./$@    






                                                  
                  
                              
                  
