# 目标：编译、运行并删除 test 测试程序

fopen_test : fopen_test.c
	$(CC) -o $@ $^   # 编译生成可执行文件
	./$@             #  
	rm ./$@                


fclose_test : fclose_test.c
	$(CC) -o $@ $^   # 编译生成可执行文件
	./$@             #  
	rm ./$@                                                      
                  
